### ISSUE TITLE
我司具有通用webApi，任何后台语言都可以调用，有兴趣合作么？

### ISSUE THREAD

**Issue by LiChangXing** [AwakenCN/InChat#25]
我司专业提供微信个人号API商业对接，服务 SCRM、机器人、群控、群管理、营销系统、电商 金融行业等研发型公司 ，主要提供微信API技术服务，有兴趣可以微信加我好友LoChaX，个人开发者勿扰哦~ 文档地址：https://wkteam.gitbook.io/doc/

**Comment by UncleCatMySelf** [comment]
/
