### ISSUE TITLE
http三个接口请求路径地址名字不一致

### ISSUE THREAD

**Issue by danrzhu** [AwakenCN/InChat#29]
比如服务器端推送 send_from_server，为什么还有一个/uri_send_from_server。
看了你的版本介绍1.1.2的使用，截图也是用：[ip:端口]/send_from_server （POST请求），
实际我测试使用发现使用[ip:端口]/uri_send_from_server才行，是我哪里用错了吗？
正在学习，我新手想问下，在controller层中调用send_from_server能进行服务端推送吗？

**Comment by UncleCatMySelf** [comment]
是的，涉及http的接口在1.1.2后做了整改

**Comment by danrzhu** [comment]
> 是的，涉及http的接口在1.1.2后做了整改

明白了，谢谢。能否再问下这个三个接口我有办法在自己的service层调用吗

**Comment by UncleCatMySelf** [comment]
后续会有Spring Boot的版本支持直接调用
